spring:
  h2:
    console:
      enabled: true
      path: /h2A
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE;IGNORECASE=TRUE;MODE=MYSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/data.sql
  jackson:
    property-naming-strategy: SNAKE_CASE
